#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Enable custom completion
fpath=(~/.zfunc $fpath)
autoload -Uz compinit && compinit -i

# Enable bash style completion
autoload -U +X bashcompinit && bashcompinit

# for Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home

# Nodenv
export NODENV_ROOT="${HOME}/.nodenv"
export PATH="${NODENV_ROOT}/bin:${PATH}"
if (( ${+commands[nodenv]} )); then
  eval "$(nodenv init -)"
fi
if [[ -e /usr/local/opt/nodenv/completions/nodenv.zsh ]]; then
  source /usr/local/opt/nodenv/completions/nodenv.zsh
fi